const KEY = /^[a-z0-9_.-]+(\/[a-z0-9_.-]+)*$/;

/** Object keys are generated by the app, never taken from user input; this is the last line of defence. */
export function assertStorageKey(key: string): string {
  if (
    key.length === 0 ||
    key.length > 512 ||
    !KEY.test(key) ||
    key.split("/").some((part) => part === "..")
  ) {
    throw new RangeError(`Invalid storage key: "${key}"`);
  }
  return key;
}
